Awesome book
LionRouge1/AwesomeBook_ES6 pull request #1
Opened 2022-02-22 15:18 UTC by LionRouge1

Awesome books: with ES6

2022-02-22 16:27 UTC, Lameck1 requested changes
Hi, @LionRouge1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 23:28 UTC, FrederickMih requested changes
Hi @LionRouge1 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 23:28 UTC, FrederickMih commented on index.js
> +}
- [ ] Hi @LionRouge1 , remember the main goal of this project is to understand the usage of ES6 arrow functions syntax and modules. Please let's stay away from traditional function expression syntax and make use of [ES6 arrow function syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

2022-02-22 23:28 UTC, FrederickMih commented on index.js
> +  element.addEventListener('click', function () {
- [ ] As pointed above, let's completely stay away from the `function` keyword.

2022-02-22 23:28 UTC, FrederickMih commented on modules/display.js
> +export default function displayBook(book) {
- [ ] I will be happy if we can start making use of [ES6 arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

2022-02-22 23:28 UTC, FrederickMih commented on modules/flashMessage.js
> +export default function snaker(type, mes, time = 4000) {
- [ ] Please no function keyword anymore. :angry:

2022-02-22 23:28 UTC, FrederickMih commented on modules/navbar.js
> +export default function showBlock(e) {
- [ ] Please let's stay away from the function keyword in this project.

2022-02-23 01:13 UTC, omar-labana requested changes
Hi @LionRouge1, 

Excellent work so far implementing the changes requested by the previous reviewer/s! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] I can see that you have refactored some of the functions to use arrow syntax instead of the functions keyword but not all of them. Kindly, make use of the text editor's search functionality   and search for the keyword `function` (I recommend using VSCode), you will find two functions in the codebase that are still using it(previously highlighted by the reviewers) and one comment, please update them.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-23 01:23 UTC, merged